### ISSUE TITLE
Use of undeclared type 'ValidationManager'

### ISSUE THREAD

**Issue by Jake-Piatkowski** [poetmountain/PapersPlease#1]
Hi,

I'm having a problem trying to use your pod (version 0.2.2). I get the "Use of undeclared type" errors whenever I'm trying to use any of your classes, such as 
`let validationManager: ValidationManager = ValidationManager();`

I thought maybe I should add an import statement so I did
`import PapersPlease`
but that doesn't help at all.

I'm fairly new to Swift - am I missing anything?

**Comment by poetmountain** [comment]
Sorry for the long delay; `0.3.2` should fix these access issues.
